<?php

/**
 * @file
 * Primary module hooks for "editorjs_media" module.
 */

use \Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function editorjs_media_theme() {
  return [
    'ce_block__media_image' => [
      'base hook' => 'ce_block',
    ],
  ];
}

/**
 * Prepare variables for 'ce_block__media_image' template.
 */
function template_preprocess_ce_block__media_image(&$variables) {
  $media = \Drupal::service('entity.repository')->loadEntityByUuid('media', $variables['data']['uuid']);
  if (empty($media)) {
    return;
  }

  if (!empty($variables['data']['view_mode'])) {
    $variables['data']['media'] = \Drupal::entityTypeManager()
      ->getViewBuilder('media')
      ->view($media, $variables['data']['view_mode']);
  }
  else {
    $theme = empty($variables['data']['image_style']) ? 'image' : 'image_style';
    $fid = $media->getSource()->getSourceFieldValue($media);
    if ($fid && $file = File::load($fid)) {
      $variables['data']['media'] = [
        '#theme' => $theme,
        '#style_name' => $variables['data']['image_style'] ?? NULL,
        '#uri' => $file->getFileUri(),
      ];
    }
  }
  $variables['#attached']['library'][] = 'editorjs_media/media_image';
}
