<?php

/**
 * @file
 * Primary module hooks for Editor.js for paragraph module.
 */

/**
 * Implements hook_theme().
 */
function editorjs_theme() {
  return [
    'ce_blocks' => [
      'render element' => 'elements',
      'file' => 'editorjs.theme.inc',
    ],
    'ce_default' => [
      'variables' => ['data' => []],
      'file' => 'editorjs.theme.inc',
    ],
    'ce_block' => [
      'variables' => ['data' => []],
      'file' => 'editorjs.theme.inc',
      'pattern' => 'ce_block__',
    ],
    'ce_block__header' => [
      'base hook' => 'ce_block',
    ],
    'ce_block__list' => [
      'base hook' => 'ce_block',
    ],
    'ce_block__delimiter' => [
      'base hook' => 'ce_block',
    ],
    'ce_block__checklist' => [
      'base hook' => 'ce_block',
    ],
    'ce_block__code' => [
      'base hook' => 'ce_block',
    ],
    'ce_block__linkTool' => [
      'base hook' => 'ce_block',
    ],
    'ce_block__image' => [
      'base hook' => 'ce_block',
    ],
    'ce_block__table' => [
      'base hook' => 'ce_block',
    ],
  ];
}
