<?php

/**
 * @file
 * Primary module hooks for Editor.js for paragraph module.
 *
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function editorjs_theme($existing, $type, $theme, $path) {
  // Base theme hook.
  $hooks['editor_js_base'] = [
    'variables' => ['data' => []],
  ];
  // Add template for default paragraph EditorJs plugin.
  $hooks['editor_js_paragraph'] = [
    'base hook' => 'editor_js_base',
  ];
  /** @var \Drupal\editorjs\EditorJsPluginManager $manager */
  $manager = \Drupal::service('plugin.manager.editorjs_plugin');
  foreach ($manager->getDefinitions() as $def) {
    if (isset($def['template']) && !empty($def['template'])){
      $hooks[$def['template']] = [
        'base hook' => 'editor_js_base',
      ];
    }
  }

  return $hooks;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function editorjs_preprocess_editor_js_base(&$variables) {
  foreach ($variables['data'] as $key => $datum) {
    if (Element::child($key)) {
      $variables[$key] = $datum;
    }
  }
}
